version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - .development.env
    ports:
      - '3306:3306'
    volumes:
      - maria_data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - '8080:8080'

volumes:
  maria_data: